//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXHvaQLKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiDangAdmin
    {
        public int MaBaiDang { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public byte[] Anh { get; set; }
        public string NguoiDang { get; set; }
    
        public virtual AccAdmin AccAdmin { get; set; }
    }
}
