//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXHvaQLKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiDangKOL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiDangKOL()
        {
            this.LuotThichBvKOLs = new HashSet<LuotThichBvKOL>();
        }
    
        public int MaBaiDang { get; set; }
        public string AccName { get; set; }
        public string Noidung { get; set; }
        public byte[] anh { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
    
        public virtual AccKOL AccKOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuotThichBvKOL> LuotThichBvKOLs { get; set; }
    }
}
