//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXHvaQLKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.LichSuGiaoDiches = new HashSet<LichSuGiaoDich>();
        }
    
        public string MaHopDong { get; set; }
        public string TenHopDong { get; set; }
        public string MaLV { get; set; }
        public string BenA { get; set; }
        public string BenB { get; set; }
        public string BenC { get; set; }
        public Nullable<System.DateTime> NgayKi { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> TriGia { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public string XacNhanHoanThanh { get; set; }
    
        public virtual AccAdmin AccAdmin { get; set; }
        public virtual AccCustomer AccCustomer { get; set; }
        public virtual AccKOL AccKOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuGiaoDich> LichSuGiaoDiches { get; set; }
    }
}
