//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXHvaQLKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuGiaoDich
    {
        public string MaTT { get; set; }
        public string MaHD { get; set; }
        public Nullable<System.DateTime> ThoiGianGD { get; set; }
        public Nullable<int> TriGia { get; set; }
    
        public virtual HopDong HopDong { get; set; }
    }
}
