//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXHvaQLKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LVKOL
    {
        public int ma { get; set; }
        public string AccName { get; set; }
        public string MaLV { get; set; }
    
        public virtual AccKOL AccKOL { get; set; }
        public virtual TTLinhVuc TTLinhVuc { get; set; }
    }
}
