//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXHvaQLKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class minitask
    {
        public int ma { get; set; }
        public Nullable<int> mavc { get; set; }
        public string Noidung { get; set; }
        public Nullable<int> trangthai { get; set; }
    
        public virtual ThoiGianBieu ThoiGianBieu { get; set; }
    }
}
