//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXHvaQLKOL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLiKOLEntities : DbContext
    {
        public QuanLiKOLEntities()
            : base("name=QuanLiKOLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccAdmin> AccAdmins { get; set; }
        public virtual DbSet<AccCustomer> AccCustomers { get; set; }
        public virtual DbSet<AccKOL> AccKOLs { get; set; }
        public virtual DbSet<AnhDang> AnhDangs { get; set; }
        public virtual DbSet<AnhKhach> AnhKhaches { get; set; }
        public virtual DbSet<BaiDangAdmin> BaiDangAdmins { get; set; }
        public virtual DbSet<BaiDangCu> BaiDangCus { get; set; }
        public virtual DbSet<BaiDangKOL> BaiDangKOLs { get; set; }
        public virtual DbSet<FaceId> FaceIds { get; set; }
        public virtual DbSet<Follow> Follows { get; set; }
        public virtual DbSet<HoiDap> HoiDaps { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<LuotThichBvKOL> LuotThichBvKOLs { get; set; }
        public virtual DbSet<LVKH> LVKHs { get; set; }
        public virtual DbSet<LVKOL> LVKOLs { get; set; }
        public virtual DbSet<minitask> minitasks { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThoiGianBieu> ThoiGianBieux { get; set; }
        public virtual DbSet<TTLinhVuc> TTLinhVucs { get; set; }
        public virtual DbSet<UngTuyenBvCu> UngTuyenBvCus { get; set; }
        public virtual DbSet<LichSuGiaoDich> LichSuGiaoDiches { get; set; }
        public virtual DbSet<RutTienKOL> RutTienKOLs { get; set; }
    }
}
