//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXHvaQLKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RutTienKOL
    {
        public int ma { get; set; }
        public string AccName { get; set; }
        public string SoTK { get; set; }
        public string NganHang { get; set; }
        public Nullable<int> SoTien { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string TenChuThe { get; set; }
    
        public virtual AccKOL AccKOL { get; set; }
    }
}
