//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXHvaQLKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.FaceIds = new HashSet<FaceId>();
        }
    
        public string AccName { get; set; }
        public string Pass { get; set; }
        public string PQ { get; set; }
        public Nullable<int> TinhTrangXT { get; set; }
        public Nullable<int> TinhTrangHD { get; set; }
        public Nullable<int> HoanThanhHS { get; set; }
        public Nullable<int> XacThuc2YT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaceId> FaceIds { get; set; }
    }
}
