$("#btn1").click(function () {
    $("#all").css('display', 'block')
    $("#amnhac").css('display', 'none')
    $("#amthuc").css('display', 'none')
    $("#thethao").css('display', 'none')
    $("#thuongmai").css('display', 'none')
    $("#mypham").css('display', 'none')
    $("#thoitrang").css('display', 'none')

    $("#btn1").css('background-color', '#014f86')
    $("#btn2").css('background-color', '#002B4E')
    $("#btn3").css('background-color', '#002B4E')
    $("#btn4").css('background-color', '#002B4E')
    $("#btn5").css('background-color', '#002B4E')
    $("#btn6").css('background-color', '#002B4E')
    $("#btn7").css('background-color', '#002B4E')
})
$("#btn2").click(function () {
    $("#all").css('display', 'none')
    $("#amnhac").css('display', 'block')
    $("#amthuc").css('display', 'none')
    $("#thethao").css('display', 'none')
    $("#thuongmai").css('display', 'none')
    $("#mypham").css('display', 'none')
    $("#thoitrang").css('display', 'none')

    $("#btn1").css('background-color', '#002B4E')
    $("#btn2").css('background-color', '#014f86')
    $("#btn3").css('background-color', '#002B4E')
    $("#btn4").css('background-color', '#002B4E')
    $("#btn5").css('background-color', '#002B4E')
    $("#btn6").css('background-color', '#002B4E')
    $("#btn7").css('background-color', '#002B4E')
})
$("#btn3").click(function () {
    $("#all").css('display', 'none')
    $("#amnhac").css('display', 'none')
    $("#amthuc").css('display', 'block')
    $("#thethao").css('display', 'none')
    $("#thuongmai").css('display', 'none')
    $("#mypham").css('display', 'none')
    $("#thoitrang").css('display', 'none')

    $("#btn1").css('background-color', '#002B4E')
    $("#btn2").css('background-color', '#002B4E')
    $("#btn3").css('background-color', '#014f86')
    $("#btn4").css('background-color', '#002B4E')
    $("#btn5").css('background-color', '#002B4E')
    $("#btn6").css('background-color', '#002B4E')
    $("#btn7").css('background-color', '#002B4E')

})
$("#btn4").click(function () {
    $("#all").css('display', 'none')
    $("#amnhac").css('display', 'none')
    $("#amthuc").css('display', 'none')
    $("#thethao").css('display', 'block')
    $("#thuongmai").css('display', 'none')
    $("#mypham").css('display', 'none')
    $("#thoitrang").css('display', 'none')

    $("#btn1").css('background-color', '#002B4E')
    $("#btn2").css('background-color', '#002B4E')
    $("#btn3").css('background-color', '#002B4E')
    $("#btn4").css('background-color', '#014f86')
    $("#btn5").css('background-color', '#002B4E')
    $("#btn6").css('background-color', '#002B4E')
    $("#btn7").css('background-color', '#002B4E')
})
$("#btn5").click(function () {
    $("#all").css('display', 'none')
    $("#amnhac").css('display', 'none')
    $("#amthuc").css('display', 'none')
    $("#thethao").css('display', 'none')
    $("#thuongmai").css('display', 'none')
    $("#mypham").css('display', 'none')
    $("#thoitrang").css('display', 'block')

    $("#btn1").css('background-color', '#002B4E')
    $("#btn2").css('background-color', '#002B4E')
    $("#btn3").css('background-color', '#002B4E')
    $("#btn4").css('background-color', '#002B4E')
    $("#btn5").css('background-color', '#014f86')
    $("#btn6").css('background-color', '#002B4E')
    $("#btn7").css('background-color', '#002B4E')
})
$("#btn6").click(function () {
    $("#all").css('display', 'none')
    $("#amnhac").css('display', 'none')
    $("#amthuc").css('display', 'none')
    $("#thethao").css('display', 'none')
    $("#thuongmai").css('display', 'block')
    $("#mypham").css('display', 'none')
    $("#thoitrang").css('display', 'none')

    $("#btn1").css('background-color', '#002B4E')
    $("#btn2").css('background-color', '#002B4E')
    $("#btn3").css('background-color', '#002B4E')
    $("#btn4").css('background-color', '#002B4E')
    $("#btn5").css('background-color', '#002B4E')
    $("#btn6").css('background-color', '#014f86')
    $("#btn7").css('background-color', '#002B4E')
})
$("#btn7").click(function () {
    $("#all").css('display', 'none')
    $("#amnhac").css('display', 'none')
    $("#amthuc").css('display', 'none')
    $("#thethao").css('display', 'none')
    $("#thuongmai").css('display', 'none')
    $("#mypham").css('display', 'block')
    $("#thoitrang").css('display', 'none')

    $("#btn1").css('background-color', '#002B4E')
    $("#btn2").css('background-color', '#002B4E')
    $("#btn3").css('background-color', '#002B4E')
    $("#btn4").css('background-color', '#002B4E')
    $("#btn5").css('background-color', '#002B4E')
    $("#btn6").css('background-color', '#002B4E')
    $("#btn7").css('background-color', '#014f86')
})

$(".detail").click(function () {
    $("#popup").css('display', 'flex')
    setTimeout(function () {
        $("#popup").css('display', 'none')
    }, 3000)
}
)